#!/bin/bash
set -e

INSTALL_USER=${SUDO_USER:-root}
SERVICE=sonosphere.service

SERVICE_FILE="/etc/systemd/system/${SERVICE}"
sed -i "s/\$USER/${INSTALL_USER}/g" "$SERVICE_FILE"

systemctl daemon-reload
systemctl enable $SERVICE || true
systemctl start $SERVICE || true